### ISSUE TITLE
No videos specified in the config.videos

### ISSUE THREAD

**Issue by Adarsh777** [calebkish/wistia-downloader#1]
Hello,

I'm using it in windows and getting this error,
**There are no videos specified in the config.videos**

I have pasted the wistia link but it giving me that error.

**Comment by calebkish** [comment]
Please paste your `config.py` in a code block

**Comment by Adarsh777** [comment]
Here is the code

`<p><a href="https://www.superhi.com/student/plan-design-code/lesson-1/our-client-appears?wvideo=zujf43fjv4"><img src="https://embed-fastly.wistia.com/deliveries/b2befd0da684f8b9431696295f9969598bf5c223.jpg?image_play_button_size=2x&amp;image_crop_resized=960x540&amp;image_play_button=1&amp;image_play_button_color=2727e6e0" width="400" height="225" style="width: 400px; height: 225px;"></a></p><p><a href="https://www.superhi.com/student/plan-design-code/lesson-1/our-client-appears?wvideo=zujf43fjv4">Our client appears! – Plan, Design + Code Your First Website – SuperHi</a></p>`

**Comment by Adarsh777** [comment]
Hey @calebkish,

Sorry, I forgot to remove the hashtags in front of code thats why the error is came. 
But after I remove the hashtags I come up with this error
![image](https://user-images.githubusercontent.com/20425116/82669302-d9999e80-9c58-11ea-9e30-dd20c64a0b8e.png)


Here is my code `config.py` code

```
 NOTICE: Chromedriver is requred for this to work.
 Download: https://chromedriver.chromium.org/
 Make sure to install the version that corresponds to your installed Chrome 
 browser version


 The 'link' can be found by right-clicking the Wistia embeded video player and 
 clicking "Copy link and thumbnail".

 The 'path' must have an ending "/" (indicates that it is a folder)

 The 'filename' will have ".mp4" appended onto it later
videos = [
     {
         'link': '<p><a href="https://www.superhi.com/student/plan-design-code/lesson-1/qr5xthoalh?wvideo=qr5xthoalh"><img src="https://embed-fastly.wistia.com/deliveries/b49dcfe0649f588b60201b3fe7e591e2.jpg?image_play_button_size=2x&amp;image_crop_resized=960x540&amp;image_play_button=1&amp;image_play_button_color=2727e6e0" width="400" height="225" style="width: 400px; height: 225px;"></a></p><p><a href="https://www.superhi.com/student/plan-design-code/lesson-1/qr5xthoalh?wvideo=qr5xthoalh">Welcome to the Plan, Design + Code Your First Website course – Plan, Design + Code Your First Website – SuperHi</a></p>',
         'path': 'path/to/file/',
         'filename': 'Video 1'
     },
     {
         'link': '<p><a href="https://www.superhi.com/student/plan-design-code/lesson-1/our-client-appears?wvideo=zujf43fjv4"><img src="https://embed-fastly.wistia.com/deliveries/b2befd0da684f8b9431696295f9969598bf5c223.jpg?image_play_button_size=2x&amp;image_crop_resized=960x540&amp;image_play_button=1&amp;image_play_button_color=2727e6e0" width="400" height="225" style="width: 400px; height: 225px;"></a></p><p><a href="https://www.superhi.com/student/plan-design-code/lesson-1/our-client-appears?wvideo=zujf43fjv4">Our client appears! – Plan, Design + Code Your First Website – SuperHi</a></p>',
         'path': 'path/to/file/',
         'filename': 'really-cool-file-name-2'
     }
]

 720 is the desired quality, and if it doesn't exist then a subsequent quality 
 will be chosen. Rearrange as desired.

 Available qualities: 1080, 720, 540, 360, 224
qualities = [
    '1080',
    '720',
    '540',
    '360',
    '224'
]

```

**Comment by calebkish** [comment]
For future reference, please also paste your errors into code blocks. Make sure you have Chromedriver properly installed; a tutorial is here: https://www.youtube.com/watch?v=dz59GsdvUF8

It looks like there is an error relating to your Bluetooth adapter as well. It might be worth disabling it in Device Manager in Windows and seeing if the program is able to run after that.

Due to my current Linux setup this isn't really something I can test right now, you're kind of on your own unfortunately.

All in all, please examine your errors before making issues. I recommend you learn the [basics of python](https://www.w3schools.com/python/python_intro.asp) before proceeding any further with the issue.

**Comment by Adarsh777** [comment]
@calebkish Okay will try disabling the Bluetooth adapter and let you know.
